version: '3.8'

services:
  go-backend:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - monitoring
    environment:
      - PROMETHEUS_PORT=8080

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./service/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - monitoring
    depends_on:
      - prometheus
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage: grafana-storage-volume

networks:
  monitoring:
    driver: bridge
